source 'http://rubygems.org'

gem 'rails', '>=2.3.5', '<3.0.0'

gem 'active-fedora'
gem 'authlogic', '>=0.1.0'
gem 'builder'
gem 'block_helpers'
gem 'columnize'
gem 'crack'
gem 'curb', '0.6.9'
gem 'database_cleaner'
gem 'diff-lcs'
gem 'facets', '2.8.4'
gem 'fastercsv', '1.5.4'
gem 'haml'
gem 'httparty'
gem 'json_pure', '>1.4.3'
gem 'linecache'
gem 'marc'
gem 'mime-types'
gem 'multipart-post'
gem 'mysql', '2.8.1'
gem 'nokogiri', '1.4.3.1'
gem 'om', '>=1.0.1'
gem 'rack'
gem 'rack-test'
gem 'rake'
gem 'RedCloth', '4.2.7'
gem 'ruby-xslt', '0.9.8'
gem 'rdoc'
gem 'rcov'
gem 'rsolr', '0.12.1'
gem 'rsolr-ext', '0.12.1'
gem 'solr-ruby' 
gem 'solrizer', '>=1.0.1'
gem 'solrizer-fedora', '>=1.0.1'
gem 'term-ansicolor'
gem 'trollop'
gem 'webrat'
gem 'will_paginate'
gem 'xml-simple'
gem 'yard'
gem 'blacklight-sitemap'

group :development, :test do
  gem 'ruby-debug'
  gem 'ruby-debug-base'
  gem 'rspec', '<2.0.0'  
  gem 'rspec-rails', '<2.0.0' # rspec-rails 2.0.0 requires Rails 3.
  gem 'mocha'
  gem 'cucumber', '>=0.8.5'
  gem 'cucumber-rails'
  gem 'gherkin'
end

group :local do
  gem 'sqlite3-ruby', '1.3.1'
end
