source 'http://rubygems.org'

gem 'rails', '>=2.3.5', '<3.0.0'

gem 'active-fedora', '>=1.2.2'  
gem 'authlogic', '>=0.1.0'
gem 'builder'
gem 'columnize'
gem 'crack'
gem 'curb'
gem 'database_cleaner'
gem 'diff-lcs'
gem 'facets'
gem 'haml'
gem 'httparty'
gem 'json_pure', '>1.4.3'
gem RUBY_VERSION.to_f < 1.9 ? 'linecache': 'linecache19' 
gem 'marc'
gem 'mime-types'
gem 'multipart-post'
gem 'nokogiri'
gem 'om', '>=1.0.0'
gem 'rack'
gem 'rack-test'
gem 'rake'
gem 'rcov'
gem 'RedCloth'
gem 'rsolr'
gem 'rsolr-ext'
gem 'solr-ruby'
gem 'solrizer', '>=0.2.0'
gem 'sqlite3-ruby'
gem 'term-ansicolor'
gem 'trollop'
gem 'webrat'
gem 'will_paginate'
gem 'xml-simple'

source 'http://gemcutter.org'

gem 'block_helpers'

group :development, :test do
  gem RUBY_VERSION.to_f < 1.9 ? 'ruby-debug' : 'ruby-debug19'
  gem RUBY_VERSION.to_f < 1.9 ? 'ruby-debug-base' : 'ruby-debug-base19'  
  gem 'rspec'
  gem 'rspec-rails'
  gem 'mocha'
  gem 'cucumber'
  gem 'cucumber-rails'
  gem 'gherkin'
  #gem 'test-unit', '= 1.2.3'
end
