development:
  fedora:
    url: http://fedoraAdmin:fedoraAdmin@127.0.0.1:8983/fedora  
  solr:
    url: http://localhost:8983/solr/development
test: &TEST  
  fedora:
    url: http://fedoraAdmin:fedoraAdmin@127.0.0.1:8983/fedora
  solr:
    url: http://localhost:8983/solr/development
staging:
  fedora:
    url: http://fedoraAdmin:fedoraAdmin@127.0.0.1:8983/fedora
  solr:
    url: http://localhost:8983/solr/staging
pre_production:
  fedora:
    url: https://fedoraAdmin:3Wic4uXy@fedorapprd.library.nd.edu:8443/fedora
    user: fedoraAdmin
    access_url: https://fedorapprd.library.nd.edu:8443/fedora
  solr:
    url: http://fedorapprd.library.nd.edu:8080/fedora_solr/arch-seaside
production:
  fedora:
    url: http://fedoraAdmin:fedoraAdmin@your.production.server:8080/fedora
  solr:
    url: http://your.production.server:8080/solr 
cucumber:
  <<: *TEST
cucumber:
  <<: *TEST
